source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'AJRouter_Example' do
  pod 'AJRouter',
  :path => '../'

  target 'AJRouter_Tests' do
    inherit! :search_paths

  end
end
